version: '3.8'

services:
  api:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_APP_ID}:prod
    container_name: ${DOCKERHUB_APP_ID}.api
    volumes:
      - ./:/app
      - api-dependencies:/app/node_modules
      - api-build:/app/dist

  database:
    container_name: ${DOCKERHUB_APP_ID}.database
    volumes:
      - db-data:/var/lib/postgresql/data

  webserver:    
    container_name: ${DOCKERHUB_APP_ID}.webserver

volumes:
  api-dependencies:
    name: ${DOCKERHUB_APP_ID}.api.dependencies
  api-build:
    name: ${DOCKERHUB_APP_ID}.api.build
  db-data:
    name: ${DOCKERHUB_APP_ID}.db
