version: '3.8'

services:
  api:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_APP_ID}-staging:latest
    container_name: ${DOCKERHUB_APP_ID}-staging.api
    volumes:
      - staging-api-dependencies:/app/node_modules
      - staging-api-build:/app/dist
  
  database:
    container_name: ${DOCKERHUB_APP_ID}-staging.database
    volumes:
      - staging-db-data:/var/lib/postgresql/data
  
  webserver:
    container_name: ${DOCKERHUB_APP_ID}-staging.webserver

volumes:
  staging-api-dependencies:
    name: ${DOCKERHUB_APP_ID}-staging.api.dependencies
  staging-api-build:
    name: ${DOCKERHUB_APP_ID}-staging.api.build
  staging-db-data:
    name: ${DOCKERHUB_APP_ID}-staging.db
