version: '3.8'

services:
  api:
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}
    networks:
      - app
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - app
    restart: unless-stopped

  webserver:    
    image: nginx:latest
    container_name: ${DOCKERHUB_APP_ID}.webserver
    volumes:
      - ./docker/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT_HTTP}:80"
      - "${APP_PORT_HTTPS}:443"
    networks:
      - app
    depends_on:
      - api
    restart: unless-stopped

networks:
  app:
    driver: bridge
    name: ${DOCKERHUB_APP_ID}.app
