name: Build and Push to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push api image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./docker/api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_ID }}-staging:latest
    
    - name: Create .env file from secrets
      uses: 0ndt/envfile@v2
      with:
        secrets: ${{ toJSON(secrets) }}
        exclude: VPS_SSH_KEY, PRODUCTION_*
    
    - name: Upload .env to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        key: |
          ${{ secrets.VPS_SSH_KEY }}
        source: ".env"
        target: "/opt/${{ secrets.DOCKERHUB_APP_ID }}/staging"
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        key: |
          ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /opt/${{ secrets.DOCKERHUB_APP_ID }}/staging
          git pull
          sed -i '/^PRODUCTION_/d' .env
          docker-compose pull
          docker-compose -f docker-compose.yml -f docker-compose.staging.yml up -d
